services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
    - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
  db:
    image: postgres:13-alpine
    environment:
        POSTGRES_PASSWORD: root
        POSTGRES_DB: nest